server:
  port: 9196

spring:
  jpa:    defer-datasource-initialization: true
  application:
    name: CONFIG-SERVER
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  profiles:
    active: jdbc
  cloud:
    config:
      enabled: true
      server:
        jdbc:
          sql: "SELECT properties.config_key, properties.config_value from properties where application_id=? and profile=? and label=?"
          order: 1
  h2:
    console:
      enabled: true
      
 

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost    